name: Build H2 VPN

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4.0.1
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '13114758'
        packages: 'platforms;android-36.1 build-tools;36.1.0 platform-tools'

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          --channel=0 \
          --install "ndk;28.2.13676358"
        echo "NDK_HOME=$ANDROID_HOME/ndk/28.2.13676358" >> $GITHUB_ENV
        sed -i '10i\
        \
            ndkVersion = "28.2.13676358"' V2rayNG/app/build.gradle.kts

    - name: Clone hev-socks5-tunnel
      run: |
        rm -rf hev-socks5-tunnel
        git clone --recursive https://github.com/heiher/hev-socks5-tunnel.git

    - name: Build libhevtun
      run: bash compile-hevtun.sh

    - name: Copy libhevtun
      run: cp -r libs V2rayNG/app/

    - name: Download libv2ray
      uses: robinraju/release-downloader@v1.13
      with:
        repository: '2dust/AndroidLibXrayLite'
        tag: 'v26.4.19'
        fileName: 'libv2ray.aar'
        out-file-path: V2rayNG/app/libs/

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Decode Keystore
      uses: timheuer/base64-to-file@v1.2.4
      id: android_keystore
      with:
        fileName: "h2vpn.jks"
        encodedString: ${{ secrets.KEYSTORE_BASE64 }}

    - name: Build APK
      run: |
        cd V2rayNG
        echo "sdk.dir=${ANDROID_HOME}" > local.properties
        chmod 755 gradlew
        ./gradlew licenseFdroidReleaseReport
        ./gradlew assembleFdroidRelease -PABI_FILTERS=arm64-v8a \
          -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }} \
          -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: h2vpn-apk
        path: V2rayNG/app/build/outputs/apk/fdroid/release/*.apk
